gains:
  pos: {x: 7.4, y: 7.4, z: 10.4}
  vel: {x: 4.8, y: 4.8, z: 6.0}
  ki:  {x: 0.00, y: 0.00, z: 0.00}
  kib: {x: 0.00, y: 0.00, z: 0.00}
  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}

corrections:
  kf: 0.0e-08
  r: 0.0
  p: 0.0

max_pos_int:   0.5
max_pos_int_b: 0.5

number_of_robots: 3

quadrotor_name: dragonfly1
mass: 0.5
payload_mass: 0.5
cable_length: 0.25

attachment:
  rho_0: {x: 1.000, y: 0.000, z: 0.000}
  rho_1: {x: -0.500, y: 0.866, z: 0.000}
  rho_2: {x: -0.500, y: -0.866, z: 0.000}
