gains:
  pos: {x: 1.8, y: 1.8, z: 3.0}
  vel: {x: 0.6, y: 0.6, z: 1.7}
  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}
  ki:  {x: 0.00, y: 0.001, z: 0.008}
  kib: {x: 0.00, y: 0.00, z: 0.00}

corrections:
  kf: 0.0e-08
  r: 0.0
  p: 0.0

max_pos_int:   0.5
max_pos_int_b: 0.5

number_of_robots: 1

quadrotor_name: dragonfly11
mass: 0.250 # redundant of robot_mass
robot_mass: 0.250
payload_mass: 0.025
cable_length: 0.5
my_index: 0

k_pos_0: 20.0
k_vel_0: 0.0
k_R_0: 0.0
k_Omega_0: 0.0
k_q: 50.0
k_w: 0.0

pl_vel_lowpass_alpha: 0.05
pl_vel_jumpmax: 0.5

attachment:
  rho_0: {x: 0.000, y: 0.000, z: 0.000}
  #rho_1: {x: -0.500, y: 0.866, z: 0.000}
  #rho_2: {x: -0.500, y: -0.866, z: 0.000}
