
kp_pos_0: {x: 2.5, y: 2.5, z: 14}
kd_pos_0: {x: 1.1, y: 1.1, z: 3.2}
ki_pos_0: {x: 0.002, y: 0.002, z: 0.003}
max_pos_0_int: 1.0

k_R_0: {x: 0.0, y: 0.08, z: 0.08}
k_Omega_0: {x: 0.0, y: 0.03, z: 0.03}
ki_R_0: {x: 0.0, y: 0.001, z: 0.001}
max_R_0_int: 1.0

kp_q: 24
ki_q: 0.0
max_e_q_int: 1.0
kd_q: 2.5

tau_q_i: 0.015
tau_q_i_dot: 0.015
tau_w_i: 0.015
