max_pos_0_int: 1.0

kp_pos_0: {x: 2.9, y: 2.9, z: 14}
ki_pos_0: {x: 0.003, y: 0.003, z: 0.003}
kd_pos_0: {x: 1.1, y: 1.1, z: 3.2}

k_R_0: {x: 0.01, y: 0.13, z: 0.2}
k_Omega_0: {x: 0.0, y: 0.011, z: 0.014}

kp_q: 23
ki_q: 0.6
max_e_q_int: 5.0
kd_q: 2.7

tau_q_i: 0.015
tau_q_i_dot: 0.015
tau_w_i: 0.015
