max_pos_0_int: 1.0

kp_pos_0: {x: 3.1, y: 3.1, z: 12}
ki_pos_0: {x: 0.001, y: 0.001, z: 0.001}
kd_pos_0: {x: 1.3, y: 1.3, z: 3.0}

k_R_0: {x: 0.0, y: 0.0, z: 0.0}
k_Omega_0: {x: 0.0, y: 0.0, z: 0.0}

kp_q: 30
ki_q: 0.7
max_e_q_int: 5.0
kd_q: 2.6

tau_q_i: 0.012
tau_q_i_dot: 0.012
tau_w_i: 0.012
