max_pos_0_int: 2.0

kp_pos_0: {x: 3.3, y: 3.3, z: 14}
ki_pos_0: {x: 0.003, y: 0.003, z: 0.003}
kd_pos_0: {x: 1.1, y: 1.1, z: 3.2}

k_R_0: {x: 0.0, y: 0.0, z: 0.0}
k_Omega_0: {x: 0.0, y: 0.0, z: 0.0}

kp_q: 24
ki_q: 0.6
max_e_q_int: 5.0
kd_q: 2.7

tau_q_i: 0.015
tau_q_i_dot: 0.015
tau_w_i: 0.015
